// frontend/src/app/components/property/property-card.component.ts
import { Component, Input, Output, EventEmitter, signal, OnInit } from '@angular/core';
import { DecimalPipe } from '@angular/common';
import type { Property, Recommendation } from '../../core/models/relocation.models';

const AMENITY_LABELS: Record<string, string> = {
  'high-speed internet': 'WiFi', internet: 'WiFi', wifi: 'WiFi',
  gym: 'Gym', metro: 'Metro', parking: 'Parking',
  security: 'Secure', '24/7 security': 'Secure', pool: 'Pool',
  'power backup': 'Backup', 'swimming pool': 'Pool',
  'modular kitchen': 'Kitchen',
  '1bhk':'1BHK','2bhk':'2BHK','3bhk':'3BHK','4bhk':'4BHK',
  '1 bhk':'1BHK','2 bhk':'2BHK','3 bhk':'3BHK','4 bhk':'4BHK',
};
const SKIP_TAGS = new Set([
  'magicbricks','housing.com','99acres','nobroker','housing','makaan',
  'dataset-imported','scraped','api-imported','no data','n/a','na',
  'furnished','unfurnished','semi-furnished','semi furnished',
  'fully furnished','partially furnished',
]);

function labelAmenity(raw: string): string {
  return AMENITY_LABELS[raw.toLowerCase()] ?? raw;
}

@Component({
  selector: 'app-property-card',
  standalone: true,
  imports: [DecimalPipe],
  templateUrl: './property-card.component.html',
  styleUrl: './property-card.component.scss',
})
export class PropertyCardComponent implements OnInit {
  @Input({ required: true }) property!: Property;
  @Input() recommendation?: Recommendation;
  @Input() index?: number;
  @Input() isActive = false;
  @Output() onClick = new EventEmitter<void>();

  showModal = signal(false);

  get totalScore(): number | null { return this.recommendation?.score?.total ?? null; }
  get priceK(): number { return Math.round(this.property.rent / 1000); }
  get violations(): string[] { return this.recommendation?.constraint_violations ?? []; }
  get isIneligible(): boolean { return this.recommendation?.is_eligible === false; }
  get highlights(): string[] { return this.recommendation?.highlights ?? []; }
  get tradeoffs(): string[] { return this.recommendation?.tradeoffs ?? []; }

  get amenityTags(): string[] {
    return this.property.amenities
      .filter((a) => !SKIP_TAGS.has(a.toLowerCase()) && a.length > 1 && a.length < 28)
      .slice(0, 3)
      .map(labelAmenity);
  }

  get scorePillClass(): string {
    const s = this.totalScore ?? 0;
    if (s >= 85) return 'score-pill score-high';
    if (s >= 72) return 'score-pill score-mid';
    if (s >= 60) return 'score-pill score-fair';
    return 'score-pill score-low';
  }

  get scoreColor(): string {
    const s = this.totalScore ?? 0;
    if (s >= 85) return '#10b981';
    if (s >= 72) return '#38bdf8';
    if (s >= 60) return '#f59e0b';
    return '#f43f5e';
  }

  get subscores(): Array<{key:string; label:string; score:number; weight:number; contribution:number; details:string}> {
    const ss = this.recommendation?.score?.subscores;
    if (!ss) return [];
    return Object.entries(ss).map(([key, d]) => ({ key, ...d }));
  }

  getColor(score: number): string {
    if (score >= 85) return '#10b981';
    if (score >= 72) return '#38bdf8';
    if (score >= 60) return '#f59e0b';
    return '#f43f5e';
  }

  openModal(e: Event): void {
    e.stopPropagation();
    this.showModal.set(true);
  }

  ngOnInit(): void {}
}

<div
  class="card"
  [class.active]="isActive"
  [class.ineligible]="isIneligible"
  (click)="onClick.emit()"
>
  <div class="badge" [class.badge-active]="isActive">{{ (index ?? 0) + 1 }}</div>

  <div class="body">
    <!-- Row 1: locality + score + price -->
    <div class="top-row">
      <div class="location-block">
        <div class="locality-row">
          <span class="locality">{{ property.locality ?? property.city ?? '—' }}</span>
          @if (totalScore !== null) {
            <span class="score-pill" [class]="scorePillClass">★ {{ totalScore }}</span>
          }
        </div>
        @if (property.city && property.locality) {
          <span class="city">{{ property.city }}</span>
        }
      </div>
      <div class="price-block">
        <span class="price">₹{{ priceK }}k</span>
        <span class="price-suffix">/mo</span>
      </div>
    </div>

    <!-- Row 2: type & furnishing -->
    <p class="subtitle">
      {{ property.property_type }}{{ property.furnishing ? ' · ' + property.furnishing : '' }}
    </p>

    <!-- Violations -->
    @if (violations.length > 0) {
      <div class="violation-tag">
        <span>⚠</span><span>{{ violations[0] }}</span>
      </div>
    }

    <!-- Tags -->
    <div class="tags">
      @if (property.commute_estimate_minutes !== null && property.commute_estimate_minutes !== undefined) {
        <span class="tag tag-commute">⏱ {{ property.commute_estimate_minutes }}&thinsp;min</span>
      }
      @if (property.distance_to_office_km !== null && property.distance_to_office_km !== undefined) {
        <span class="tag">📍 {{ property.distance_to_office_km!.toFixed(1) }}&thinsp;km</span>
      }
      @for (t of amenityTags; track t) {
        <span class="tag">{{ t }}</span>
      }
    </div>

    <!-- Highlights -->
    @if (highlights.length > 0) {
      <div class="why-row">
        @for (h of highlights.slice(0, 2); track h) {
          <span class="why-tag">✓ {{ h }}</span>
        }
      </div>
    }

    <!-- Explain Score -->
    @if (recommendation) {
      <button type="button" class="explain-btn" (click)="openModal($event)">
        <span>✦</span>
        <span>Explain Score & Factors</span>
        <span>›</span>
      </button>
    }
  </div>

  @if (isActive) { <div class="accent-bar"></div> }
</div>

<!-- Score Breakdown Modal -->
@if (showModal() && recommendation) {
  <div class="modal-backdrop" (click)="showModal.set(false)">
    <div class="modal" (click)="$event.stopPropagation()">
      <div class="modal-header">
        <div>
          <div class="modal-tag-row">
            <span class="profile-badge">✦ {{ (recommendation.scoring_profile ?? 'balanced').replace('_', ' ').toUpperCase() }}</span>
            @if (recommendation.rank) { <span class="rank-badge">Rank #{{ recommendation.rank }}</span> }
          </div>
          <h2 class="modal-title">{{ property.title }}</h2>
          <p class="modal-locality">{{ property.locality || property.city || 'Kolkata' }} · ₹{{ property.rent.toLocaleString('en-IN') }}/mo</p>
        </div>
        <button type="button" class="close-btn" (click)="showModal.set(false)">✕</button>
      </div>

      <div class="score-hero">
        <div class="score-circle" [style.border-color]="scoreColor">
          <span class="score-num" [style.color]="scoreColor">{{ totalScore ?? 75 }}</span>
          <span class="score-max">/ 100</span>
        </div>
        <div>
          <h3 class="score-heading">Composite Match Score</h3>
          <p class="score-sub">Calculated using 7 weighted criteria &amp; active persona.</p>
        </div>
        <div class="confidence-pill">
          📈 {{ recommendation.score.confidence_score ?? 85 }}% Confidence
        </div>
      </div>

      @if (violations.length > 0) {
        <div class="violations-card">
          <strong>⚠ Hard Constraint Violations</strong>
          <ul>@for (v of violations; track v) { <li>{{ v }}</li> }</ul>
        </div>
      }

      @if (subscores.length > 0) {
        <div class="factors-section">
          <h4>Weighted Factor Breakdown</h4>
          @for (item of subscores; track item.key) {
            <div class="factor-item">
              <div class="factor-header">
                <span class="factor-name">{{ item.label }}</span>
                <span class="factor-score" [style.color]="getColor(item.score)">{{ item.score }}/100</span>
                <span class="factor-weight">({{ (item.weight * 100) | number:'1.0-0' }}% wt → +{{ item.contribution }} pts)</span>
              </div>
              <div class="bar-track">
                <div class="bar-fill" [style.width.%]="item.score" [style.background-color]="getColor(item.score)"></div>
              </div>
              @if (item.details) { <p class="factor-details">{{ item.details }}</p> }
            </div>
          }
        </div>
      }

      <div class="insights-grid">
        @if (highlights.length > 0) {
          <div class="insight-box positive">
            <h5>✔ Key Strengths</h5>
            <ul>@for (h of highlights; track h) { <li>{{ h }}</li> }</ul>
          </div>
        }
        @if (tradeoffs.length > 0) {
          <div class="insight-box negative">
            <h5>⚠ Tradeoffs</h5>
            <ul>@for (t of tradeoffs; track t) { <li>{{ t }}</li> }</ul>
          </div>
        }
      </div>

      <div class="explanation-box">
        <strong>✦ AI Recommendation Context</strong>
        <p>{{ recommendation.score.explanation }}</p>
      </div>
    </div>
  </div>
}

// frontend/components/property/property-card.tsx
"use client";

import { useState } from "react";
import { motion } from "framer-motion";
import { Clock, MapPin, Sparkles, AlertTriangle, ChevronRight } from "lucide-react";
import type { Property, Recommendation } from "@/types";
import { ScoreBreakdownModal } from "./score-breakdown-modal";
import styles from "./property-card.module.css";

interface PropertyCardProps {
  property: Property;
  recommendation?: Recommendation;
  index?: number;
  isActive?: boolean;
  onClick?: () => void;
}

const AMENITY_LABELS: Record<string, string> = {
  "high-speed internet": "WiFi",
  internet: "WiFi",
  wifi: "WiFi",
  gym: "Gym",
  metro: "Metro",
  parking: "Parking",
  security: "Secure",
  "24/7 security": "Secure",
  pool: "Pool",
  "power backup": "Backup",
  "swimming pool": "Pool",
  "modular kitchen": "Kitchen",
  "1bhk": "1BHK",
  "2bhk": "2BHK",
  "3bhk": "3BHK",
  "4bhk": "4BHK",
  "1 bhk": "1BHK",
  "2 bhk": "2BHK",
  "3 bhk": "3BHK",
  "4 bhk": "4BHK",
};

const SKIP_TAGS = new Set([
  "magicbricks",
  "housing.com",
  "99acres",
  "nobroker",
  "housing",
  "makaan",
  "dataset-imported",
  "scraped",
  "api-imported",
  "no data",
  "n/a",
  "na",
  "furnished",
  "unfurnished",
  "semi-furnished",
  "semi furnished",
  "fully furnished",
  "partially furnished",
]);

function label(raw: string): string {
  return AMENITY_LABELS[raw.toLowerCase()] ?? raw;
}

function getScoreBadgeClass(score: number): string {
  if (score >= 85) return styles.scoreHigh;
  if (score >= 72) return styles.scoreMid;
  if (score >= 60) return styles.scoreFair;
  return styles.scoreLow;
}

export function PropertyCard({
  property,
  recommendation,
  index = 0,
  isActive = false,
  onClick,
}: PropertyCardProps) {
  const [showModal, setShowModal] = useState(false);

  const commute = property.commute_estimate_minutes;
  const dist = property.distance_to_office_km;
  const priceK = Math.round(property.rent / 1000);

  const totalScore = recommendation?.score?.total;
  const violations = recommendation?.constraint_violations ?? [];
  const isEligible = recommendation?.is_eligible !== false;

  const amenityTags = property.amenities
    .filter((a) => !SKIP_TAGS.has(a.toLowerCase()) && a.length > 1 && a.length < 28)
    .slice(0, 3)
    .map(label);

  const highlights = recommendation?.highlights ?? [];

  return (
    <>
      <motion.div
        className={`${styles.card} ${isActive ? styles.active : ""} ${
          !isEligible ? styles.cardIneligible : ""
        }`}
        onClick={onClick}
        whileHover={{ y: -1 }}
        whileTap={{ scale: 0.985 }}
        transition={{ type: "spring", stiffness: 480, damping: 28 }}
      >
        {/* Left: numbered index badge */}
        <div className={`${styles.badge} ${isActive ? styles.badgeActive : ""}`}>
          {index + 1}
        </div>

        {/* Right: property info */}
        <div className={styles.body}>
          {/* Row 1 — locality + score badge + price */}
          <div className={styles.topRow}>
            <div className={styles.locationBlock}>
              <div className={styles.localityRow}>
                <span className={styles.locality}>
                  {property.locality ?? property.city ?? "—"}
                </span>
                {totalScore != null && (
                  <span
                    className={`${styles.scorePill} ${getScoreBadgeClass(totalScore)}`}
                    title="Click 'Score Breakdown' below for explainable factor contributions"
                  >
                    ★ {totalScore}
                  </span>
                )}
              </div>
              {property.city && property.locality && (
                <span className={styles.city}>{property.city}</span>
              )}
            </div>
            <div className={styles.priceBlock}>
              <span className={styles.price}>₹{priceK}k</span>
              <span className={styles.priceSuffix}>/mo</span>
            </div>
          </div>

          {/* Row 2 — property type */}
          <p className={styles.subtitle}>
            {property.property_type}
            {property.furnishing ? ` · ${property.furnishing}` : ""}
          </p>

          {/* Constraint Violations Alert if any */}
          {violations.length > 0 && (
            <div className={styles.violationTag}>
              <AlertTriangle size={10} />
              <span>{violations[0]}</span>
            </div>
          )}

          {/* Row 3 — smart tags */}
          <div className={styles.tags}>
            {commute != null && (
              <span className={`${styles.tag} ${styles.tagCommute}`}>
                <Clock size={9} /> {commute}&thinsp;min
              </span>
            )}
            {dist != null && (
              <span className={styles.tag}>
                <MapPin size={9} /> {dist.toFixed(1)}&thinsp;km
              </span>
            )}
            {amenityTags.map((t) => (
              <span key={t} className={styles.tag}>
                {t}
              </span>
            ))}
          </div>

          {/* Row 4 — Top positive highlights */}
          {highlights.length > 0 && (
            <div className={styles.whyRow}>
              {highlights.slice(0, 2).map((h, i) => (
                <span key={i} className={styles.whyTag}>
                  ✓ {h}
                </span>
              ))}
            </div>
          )}

          {/* Row 5 — Explain Score button trigger */}
          {recommendation && (
            <button
              type="button"
              className={styles.explainBtn}
              onClick={(e) => {
                e.stopPropagation();
                setShowModal(true);
              }}
            >
              <Sparkles size={10} />
              <span>Explain Score &amp; Factors</span>
              <ChevronRight size={10} />
            </button>
          )}
        </div>

        {/* Active left-edge accent bar */}
        {isActive && <div className={styles.accentBar} />}
      </motion.div>

      {/* Transparent Explainable Score Modal */}
      <ScoreBreakdownModal
        property={property}
        recommendation={recommendation}
        isOpen={showModal}
        onClose={() => setShowModal(false)}
      />
    </>
  );
}
