// frontend/components/assistant/chat-panel.tsx
"use client";

import { FormEvent, useState } from "react";
import { SendHorizonal } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { api } from "@/lib/api";
import styles from "./chat-panel.module.css";

type Message = { role: "user" | "assistant"; content: string };

export function ChatPanel() {
  const [messages, setMessages] = useState<Message[]>([
    { role: "assistant", content: "Tell me your office location, budget, commute preference, and what kind of life you want nearby." }
  ]);
  const [input, setInput] = useState("Need PG near office with metro connectivity and safe late-night commute.");
  const [isLoading, setIsLoading] = useState(false);

  async function onSubmit(event: FormEvent) {
    event.preventDefault();
    const next = input.trim();
    if (!next) return;
    setMessages((current) => [...current, { role: "user", content: next }]);
    setInput("");
    setIsLoading(true);
    try {
      const response = await api.chat(next);
      setMessages((current) => [...current, { role: "assistant", content: response.answer }]);
    } finally {
      setIsLoading(false);
    }
  }

  return (
    <Card className={styles.panel}>
      <div className={styles.messages}>
        {messages.map((message, index) => (
          <div key={index} className={`${styles.messageRow} ${message.role === "user" ? styles.fromUser : styles.fromAssistant}`}>
            <div className={`${styles.bubble} ${message.role === "user" ? styles.userBubble : styles.assistantBubble}`}>
              {message.content}
            </div>
          </div>
        ))}
        {isLoading && <div className={styles.loading}>Thinking through tradeoffs...</div>}
      </div>
      <form onSubmit={onSubmit} className={styles.form}>
        <Input value={input} onChange={(event) => setInput(event.target.value)} aria-label="Assistant message" />
        <Button type="submit" size="icon" aria-label="Send">
          <SendHorizonal size={18} />
        </Button>
      </form>
    </Card>
  );
}

// frontend/src/app/components/chat-panel/chat-panel.component.ts
import { Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ApiService } from '../../core/services/api.service';

type Message = { role: 'user' | 'assistant'; content: string };

@Component({
  selector: 'app-chat-panel',
  standalone: true,
  imports: [FormsModule],
  templateUrl: './chat-panel.component.html',
  styleUrl: './chat-panel.component.scss',
})
export class ChatPanelComponent {
  private api = inject(ApiService);

  messages = signal<Message[]>([
    { role: 'assistant', content: 'Tell me your office location, budget, commute preference, and what kind of life you want nearby.' },
  ]);
  input = 'Need PG near office with metro connectivity and safe late-night commute.';
  isLoading = signal(false);

  async onSubmit(): Promise<void> {
    const text = this.input.trim();
    if (!text) return;
    this.messages.update((prev) => [...prev, { role: 'user', content: text }]);
    this.input = '';
    this.isLoading.set(true);
    try {
      const res = await this.api.chat(text);
      this.messages.update((prev) => [...prev, { role: 'assistant', content: res.answer }]);
    } finally {
      this.isLoading.set(false);
    }
  }
}

<div class="panel">
  <div class="messages">
    @for (msg of messages(); track $index) {
      <div class="message-row" [class.from-user]="msg.role === 'user'" [class.from-assistant]="msg.role === 'assistant'">
        <div class="bubble" [class.user-bubble]="msg.role === 'user'" [class.assistant-bubble]="msg.role === 'assistant'">
          {{ msg.content }}
        </div>
      </div>
    }
    @if (isLoading()) {
      <div class="thinking">Thinking through tradeoffs…</div>
    }
  </div>
  <form class="chat-form" (ngSubmit)="onSubmit()">
    <input
      class="chat-input"
      [(ngModel)]="input"
      name="message"
      aria-label="Assistant message"
      placeholder="Ask about commute, rent, safety…"
      [disabled]="isLoading()"
    />
    <button type="submit" class="send-btn" [disabled]="isLoading()" aria-label="Send">
      ➤
    </button>
  </form>
</div>
