// frontend/src/app/components/assistant/assistant.component.ts
import { Component } from '@angular/core';
import { NavComponent } from '../nav/nav.component';
import { ChatPanelComponent } from '../chat-panel/chat-panel.component';
import { RelocationMapComponent } from '../map/relocation-map.component';

@Component({
  selector: 'app-assistant',
  standalone: true,
  imports: [NavComponent, ChatPanelComponent, RelocationMapComponent],
  templateUrl: './assistant.component.html',
  styleUrl: './assistant.component.scss',
})
export class AssistantComponent {}

<app-nav />
<main class="main">
  <section class="content">
    <h1 class="title">Conversational relocation assistant</h1>
    <p class="copy">
      Ask about office proximity, late-night commute, locality tradeoffs,
      negotiated rents, and internet reliability.
    </p>
    <div class="panel-wrap">
      <app-chat-panel />
    </div>
  </section>
  <div class="map-wrap">
    <app-relocation-map />
  </div>
</main>

// frontend/app/assistant/page.tsx
import { ChatPanel } from "@/components/assistant/chat-panel";
import { RelocationMap } from "@/components/map/relocation-map";
import { Nav } from "@/components/nav";
import styles from "./page.module.css";

export default function AssistantPage() {
  return (
    <>
      <Nav />
      <main className={styles.main}>
        <section>
          <h1 className={styles.title}>Conversational relocation assistant</h1>
          <p className={styles.copy}>
            Ask about office proximity, late-night commute, locality tradeoffs, negotiated rents, and internet reliability.
          </p>
          <div className={styles.panelWrap}>
            <ChatPanel />
          </div>
        </section>
        <RelocationMap />
      </main>
    </>
  );
}
